### PR TITLE
adding Authorization block at operation level

### PR DESCRIPTION
**Pull request by mayuranchalia**
Authorization block was not available at operation level. Changes to
include authorization block at operation level.

### CODE REVIEW

**Comment by olensmar** [comment]
Thanks! - doesn't this need to be added to the SwaggerReaderImpl as well ?

**Comment by mayuranchalia** [comment]
Yaa Olen , It is required in required in SwaggerReaderImpl  aswell , will take a look into it.
Have you integrated the changes in main branch? And Thanks for your response ....

**Comment by olensmar** [comment]
I'll merge your branch as soon as the SwaggerReaderImpl stuff is in place - thank you!

**Comment by IlyaAvdeev** [comment]
Closing due to age and conflicts, if it's still important for you please rectreate the PR and I'll merge it. Thank you!

**Pull request closed without merging**
